#!/bin/sh
set -e

getemail () {
	printf "email address> $EMAIL_ADDRESS"
	echo "$EMAIL_ADDRESS" > .registrationemail
}
echo ""
echo "To register to participate in the IA.BAK project, please"
echo "enter a contact email address."
echo ""
echo "We will keep this email private, and only use it to contact"
echo "you if there is a problem with your portion of the Internet"
echo "Archive backup."
echo ""
echo "It's important we have a way to get in touch with you,"
echo "so that this backup can be as reliable as possible!"
echo ""
getemail
